name: Main Workflow
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout LN_TEST_RANGE
        uses: actions/checkout@v4
      - name: Build big-interop-sim
        run: |
          cd big-interop-sim
          cargo build
      - name: Build simple-interop-sim
        run: |
          cd simple-interop-sim
          cargo build
